[package]
name = "rvs-c-api"
version = "0.1.0"
authors = ["Rob Donnelly <rfdonnelly@gmail.com>"]

[dependencies]
libc = "0.2"
rvs = { version = "0.1", path = ".." }

[lib]
name = "rvs"
crate-type = ["cdylib"]
